name: Test compilation

on: 
  push: # On any push on a "stable" branch
    branches:
      - master
      - 8.14
      - 8.13
      - 8.12
      - 8.11

  pull_request: # On all pull-request changes
  release: # At release time
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ local, hott, dune ]

    steps:


      - name: Get current Coq head commit
        id: get-commit
        run: |
          echo "::set-output name=hash::$(git ls-remote https://github.com/coq/coq refs/heads/master | cut -f 1)"
        shell: bash

      - name: Try to restore opam cache
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: opam-${{github.base_ref}}-${{github.ref}}-${{steps.get-commit.outputs.hash}}
          restore-keys: |
            opam--refs/heads/${{github.base_ref}}-${{steps.get-commit.outputs.hash}}

      - name: Install OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.07.1

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: opam repo add coq-released https://coq.inria.fr/opam/released
      - run: opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
      - run: opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
      - run: opam install -j 2 -y flock dune
      - run: opam install coq.dev ocamlfind.1.8.1 # Required by dune, avoids recompiling Coq later
      - run: opam upgrade -y coq.dev ocamlfind.1.8.1 # Required by dune, avoids recompiling Coq later
      - run: opam list
      - run: opam exec -- coqc --version
      - run: opam exec -- ./configure.sh --enable-${{matrix.target}}
      - run: opam exec -- make -j 2 ci-${{matrix.target}}
