name: Test compilation

on: 
  push: # On any push on a "stable" branch
    branches:
      - master
      - v8.14
      - v8.13
      - v8.12
      - v8.11

  pull_request: # On all pull-request changes
  release: # At release time
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ local, hott, dune ]

    steps:

      - name: Try to restore opam cache
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: opam-${{matrix.target}}--${{github.base_ref}}-${{github.ref}} 
          restore-keys: |
            opam-${{matrix.target}}--refs/heads/${{github.base_ref}}

      - name: Install OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.07.1

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: opam repo add coq-released https://coq.inria.fr/opam/released
      - run: opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
      - run: opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
      - run: opam install -j 2 -y coq.dev ocamlfind.1.8.1 # Required by dune, avoids recompiling Coq later
      - run: opam upgrade -y coq.dev ocamlfind.1.8.1 # Required by dune, avoids recompiling Coq later
      - run: opam list
      - run: opam exec -- coqc --version
      - run: opam exec -- ./configure.sh --enable-${{matrix.target}}
      - run: opam exec -- make -j 2 ci-${{matrix.target}}
